export const ERROR_CODES = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  RESOURCE_ARCHIVED: "RESOURCE_ARCHIVED",

  VOTING_CLOSED: "VOTING_CLOSED",
  VOTING_FROZEN: "VOTING_FROZEN",
  VOTE_LIMIT_REACHED: "VOTE_LIMIT_REACHED",
  ALREADY_VOTED_PROJECT: "ALREADY_VOTED_PROJECT",

  USER_BANNED: "USER_BANNED",
  IP_BLOCKED: "IP_BLOCKED",
  DEVICE_BLOCKED: "DEVICE_BLOCKED",
  FRAUD_SUSPECTED: "FRAUD_SUSPECTED",

  UPLOAD_TOO_LARGE: "UPLOAD_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  VIDEO_TOO_LONG: "VIDEO_TOO_LONG",
  MEDIA_PROCESSING_FAILED: "MEDIA_PROCESSING_FAILED",

  EXPORT_FAILED: "EXPORT_FAILED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  MAINTENANCE_MODE: "MAINTENANCE_MODE",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const

export type ErrorCode = keyof typeof ERROR_CODES